### ISSUE TITLE
Setup script for DB

### ISSUE THREAD

**Issue by georgandreasjaksch** [penny-vault/pv-api#124]
I’m currently trying to setup the pv-api. Having installed postgres I’m struggling to create all the needed tables from the CSVs - is there some DDL/SQLs available?

**Comment by jdfergason** [comment]
Hi, George! There is a database DDL but i have not publicly released it yet.

**Comment by jdfergason** [comment]
the pvdb database is currently not available. could you describe what you are trying to do and I could maybe point you in the right direction?

**Comment by georgandreasjaksch** [comment]
I'm following your Readme instructions to start the pv-api. However when I run `pvapi serve` there's a lot of errors being thrown (due to missing roles like `pvuser` and `pvadmin` and missing relations like `trading_days`) which I suppose the API relies on.

I'm very interested in portfolio management and being able to backtest strategies so your tool looks very interesting but maybe it's not even meant for public use?

**Comment by jdfergason** [comment]
Public use is fine but i haven’t put much time into documenting how to get it all up and running. There are quite a few moving pieces to make pv api useful. You will need:

1) pv-api
2) pvdb
3) frontend
4) data in the assets, trading-days, market-holidays, and eod tables
5) an oauth2 provider

i went ahead and made the database schema public here: 
https://github.com/penny-vault/database

**Comment by georgandreasjaksch** [comment]
Wow, thanks so much! I'll look into it and will try to bring it up and running.
